name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create test network
        run: docker network create test-net || true

      - name: Start MySQL on test-net
        run: |
          docker run -d --name test-mysql --network test-net \
            -e MYSQL_ROOT_PASSWORD=example \
            -e MYSQL_DATABASE=tododb \
            mysql:8.0
          # wait for mysql ready
          for i in $(seq 1 30); do
            docker exec test-mysql mysqladmin ping -pexample >/dev/null 2>&1 && echo "MySQL ready" && break
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Run app container with DB
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          docker run -d --name todo-app-test --network test-net \
            -e MYSQL_HOST=test-mysql \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=example \
            -e MYSQL_DB=tododb \
            ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Check app is running
        run: |
          # Wait a bit and check logs instead of curl to avoid network issues
          sleep 10
          docker logs todo-app-test --tail 50
          docker ps | grep todo-app-test || exit 1
